pid /opt/flashpaper/nginx.pid;

events {}
http {

  client_body_temp_path /opt/flashpaper/client_temp 1 2;

  fastcgi_temp_path /opt/flashpaper/fastcgi;
  proxy_temp_path /opt/flashpaper/proxy;

  scgi_temp_path /opt/flashpaper/scgi;
  uwsgi_temp_path /opt/flashpaper/uwsgi;

  server {
      listen 80;

      root /var/www/html;
      index index.php;
      access_log /dev/null;

      location / {
        include mime.types;
        try_files $uri $uri/ =404;
      }

      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/opt/flashpaper/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param REQUEST_SCHEME $http_x_forwarded_proto if_not_empty;
      }
  }
}
