; This file will be copied to the container at build time to
; /etc/php83/conf.d/99_flashpaper.ini, this allows any setting
; defined in this file to override settings from other php initialization files
[PHP]

; Redirect PHP error logs to stderr, to support a read-only container
error_log = stderr
